### ISSUE TITLE
Update project template to not require usage of ProjectReference

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#89]
As a consequence of overloading the concept of ProjectReference for a project template all the outputs of these projects are now being placed into the .vsix itself.
This is bad for a number of reasons.
Instead of ProjectReference we should change this to something else. Eventually we should create tooling for this as well.

This is impacting #87 
### Design

We should have a right-click menu option Add->Template Reference when the user invokes this he will see a dialog that show the projects loaded in the solution. When the user picks an item we should create the following item in the project file.

`<TemplateReference Include="..path\MyProj.csproj" />`

@madskristensen can you help here? Could you add the Add->Template Reference gesture and the UI to pick the project? You could reuse most of what you created for webjobs here. If you handle the UI then I can go in and implement the MSBuild code to update the project.
##### Tasks
- [ ] Add gesture in VS to add Template Reference (Mads)
- [ ] Add UI to pick the project that the Template Reference is pointing to (Mads)
- [ ] Update project file to write out TemplateReference (Sayed)
- [x] Update TemplateBuilder to support templates via TemplateReference (Sayed)
